hotfix(common > eslint): breaking change in lib
- `prettier/@typescript-eslint` should be replaced with `prettier` because of the following breaking change:
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

currently throws an error:
```
Cannot read config file: .../node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
```